tested workstation build to build in /home/ubuntu/software or custom install!

diff --git a/maali b/maali
--- a/maali
+++ b/maali
@@ -73,8 +73,9 @@ MAALI_CYGNET_DIR_NAME='cygnet_files'
 MAALI_CYGNET_BUILD_FILE_EXT='cyg'
 
 if [ ! $MYGROUP ]; then
-   maali_wiki " MYGROUP is not defined this is not on the Pawsey HPC file system line "
-   maali_wiki " root is $MAALI_ROOT as set by a system.config file"
+   maali_wiki " MYGROUP is not defined! "
+   maali_wiki " This is not on the Pawsey HPC file system line "
+   maali_wiki " root is $MAALI_ROOT as set by ${SYSTEM}.config file"
 else 
 # At the Pawsey Supercomputing Center MYGROUP is a custom system variable
 # /group/projectID where /group is parallel filesystem for storing job outputs
@@ -357,6 +358,9 @@ function maali_module {
       fi
     fi
   fi
+  echo " " 
+  echo "Maali app home is the same as the Maali install dir = $MAALI_INSTALL_DIR"
+  echo " "
 
   # used to make the module look pretty
   MAALI_MODULE_MAX_VARIABLE=${#MAALI_APP_HOME_NAME}
@@ -972,7 +976,7 @@ function maali_modify_modulepath {
 function install_default_compiler_modules {
   echo ""
   
-  if [ ! -d "$MAALI_DEFAULT_COMPILERS" ]; then
+  if [ ! -z "$MAALI_DEFAULT_COMPILERS" ]; then
     echo "list of installed compilers $MAALI_DEFAULT_COMPILERS"    
     maali_makedir "$MAALI_DEFAULT_COMPILERS/devel"
     maali_modify_modulepath 
@@ -992,6 +996,9 @@ function install_default_compiler_modules {
          echo "compiler module already exists "
        fi
     done
+    echo "exit install compiler modules"
+  else
+    echo " no default compiler set"
     echo "exit install compiler modules"
   fi
 }
@@ -1087,6 +1094,7 @@ MAALI_REBUILD_COMPILER=
 MAALI_REMODULE=0
 MAALI_BUILDONLY=
 MAALI_SYSTEM_BUILD=NO
+MAALI_WS_BUILD=0
 MAALI_CMAKE_PATH=".."
 MAALI_MAKE_VERSION_DEFAULT=0
 MAALI_FORCE_DOWNLOAD_FROM_GITHUB=0
@@ -1153,6 +1161,7 @@ do
              ;;
          w)
              MAALI_ROOT="$HOME/software/$MAALI_OS"
+             MAALI_WS_BUILD=1
              ;;
          a)
              MAALI_MAKE_VERSION_DEFAULT=1
@@ -1275,7 +1284,8 @@ MAALI_PYTHON_FIRSTLETTER=`echo "$MAALI_TOOL_NAME_ORIG" | cut -b 1`
 # or it will be it the users $HOME/.maali directory.
 #
 
-if [ "$MAALI_CONFIG" != "" ]; then
+if [ ! -z ${MAALI_CONFIG} ]; then
+   echo " !!!!!!!  Do I get here?? line 1285"
   # allow us to override the config
 # Test to see if it in the users directory
   if [ -f "$HOME/.maali/$MAALI_CONFIG.config" ]; then
@@ -1284,6 +1294,7 @@ if [ "$MAALI_CONFIG" != "" ]; then
      # use the name of our config file to create a different log file
      MAALI_LOG_PREFIX="$MAALI_CONFIG-"
   elif [ -f ${MAALI_CONFIG}.config ]; then 
+   
     #  MAALI_CONFIG exist in the maali install so we will treat this as an initial install!
     if [ ! -d ${HOME}/.maali ]; then
     #  Found the MAALI_CONFIG.config file copy to user home and source
@@ -1297,7 +1308,7 @@ if [ "$MAALI_CONFIG" != "" ]; then
 # 	echo  "!! The module devel directory has been created !!"
         install_default_compiler_modules 
       else
- 	echo " $MAALI_MODULE_DIR does not exsist"
+ 	echo " $MAALI_MODULE_DIR does not exist"
       fi
 
     fi 
@@ -1305,7 +1316,22 @@ if [ "$MAALI_CONFIG" != "" ]; then
     echo "Could not open $HOME/.maali/$MAALI_CONFIG.config!";
     exit 1;
   fi
+elif [[ -z ${MAALI_CONFIG} ]] && [[ "${MAALI_TOOL_NAME}" == "maali" ]]; then
+  echo " !!!!!!! do I get here no config but is a workstation build"
+  echo " need to test for module dir and install default compiler modules "
+  echo " echo does the maali module direct exist ${MAALI_MODULE_DIR}"
+  echo " "
+  if [ -z ${MAALI_DEFAULT_COMPILERS} ]; then
+      echo " NO Default compilers defined, install will fail"
+      echo " MAALI_DEFAULT_COMPILERS=\"gcc/4.8.3 intel/15.0.0\" ./maali -t maali -v 1.0.1"
+      exit 1
+  else 
+      install_default_compiler_modules 
+  fi
 fi
+echo " exit test for maali.config file" 
+
+
 
 # system builds require MAALI_BUILDER_UID to be defined
 if [ "$MAALI_SYSTEM_BUILD" == "YES" ]; then
@@ -1338,7 +1364,7 @@ if [ "$MAALI_SYSTEM_BUILD" == "YES" ]; then
     fi
   fi
 fi
-
+echo " exit test for system_build to set MAALI_BUILDER_UID - line 1348" 
 # need to set MAALI_DEFAULT_CRAY_GCC_PRGENV, MAALI_DEFAULT_CRAY_INTEL_PRGENV and MAALI_DEFAULT_CRAY_CCE_PRGENV
 if [ "$MAALI_DEFAULT_CRAY_PRGENVS" != "" ]; then
   for MAALI_DEFAULT_PRGENV in $MAALI_DEFAULT_CRAY_PRGENVS; do
@@ -1514,6 +1540,7 @@ if [ $MAALI_FOUND_CYGENT -eq 0 ]; then
   MAALI_FOUND_CYGENT=1
 
 fi
+echo " exit test and download cygnet files line 1524 "
 
 # source the cygnet file
 . $MAALI_CYGNET_FILEPATH
@@ -1608,7 +1635,9 @@ done
 if [ -z $MAALI_TOOL_TYPE ]; then
   MAALI_TOOL_TYPE="apps"
 fi
-
+echo " "
+echo " set tool type to apps line-1619 "
+echo " "
 if [ "$MAALI_SYSTEM_BUILD" == "YES" ]; then
   # create a wiki page to help David
   MAALI_WIKI_SRC="$HOME/.maali/$MAALI_OS/wiki/$MAALI_LOG_PREFIX$MAALI_TOOL_NAME-$MAALI_TOOL_VERSION.wiki"
@@ -1627,6 +1656,7 @@ if [ "$MAALI_SYSTEM_BUILD" == "YES" ]; then
         MAALI_COMPILER_VERSION="N/A"
         MAALI_WIKI_COMPILER_STRING="N/A"
       else
+
         maali_load_module "$MAALI_COMPILER"
 
         if [ $MAALI_PYTHON_TOOL ]; then
@@ -1691,7 +1721,7 @@ $ maali $MAALI_CMDLINE
 Using $MAALI_FILES_PATH/$MAALI_TOOL_NAME.$MAALI_CYGNET_BUILD_FILE_EXT for tool configuration information
 EOF
   fi
-
+echo " setup maali app dir and module dir line 1704 "
   # where the software is installed is based on the tool type
   MAALI_APPS_DIR="$MAALI_ROOT/$MAALI_TOOL_TYPE"
 
@@ -1701,21 +1731,37 @@ EOF
   else
     MAALI_TOOL_MODULE_DIR="$MAALI_MODULE_DIR/$MAALI_TOOL_TYPE/$MAALI_TOOL_NAME"
   fi
-else
-  echo "Warning: non-system build detected, overriding MAALI_TOOL_TYPE (currently $MAALI_TOOL_TYPE) and setting to tool type to 'apps'"
-  # for user builds we want them to be able to include a single module path
-  MAALI_TOOL_TYPE="apps"
+
+elif [[ ! -z ${MAALI_CONFIG} ]] && [[ ${MAALI_WS_BUILD} -eq 1 ]]; then
+   # this is a workstation
+   # where the software is installed is based on the tool type
+
   MAALI_APPS_DIR="$MAALI_ROOT/$MAALI_TOOL_TYPE"
+  echo " Maali will install $MAALI_TOOL_NAME in ${MAALI_APPS_DIR} directory! " 
+  # this is now based on tool type
   if [ $MAALI_CUDA_BUILD -eq 1 ]; then
-    MAALI_TOOL_MODULE_DIR="$MAALI_MODULE_DIR/$MAALI_TOOL_NAME-gpu"
+    MAALI_TOOL_MODULE_DIR="$MAALI_MODULE_DIR/$MAALI_TOOL_TYPE/$MAALI_TOOL_NAME-gpu"
   else
-    MAALI_TOOL_MODULE_DIR="$MAALI_MODULE_DIR/$MAALI_TOOL_NAME"
+    MAALI_TOOL_MODULE_DIR="$MAALI_MODULE_DIR/$MAALI_TOOL_TYPE/$MAALI_TOOL_NAME"
     # This being set during the intial maali install so all the paths come out right"
-    if [[ "${MAALI_TOOL_NAME}" == "maali" ]] && [[ ! -z ${MAALI_CONFIG} ]]; then
-    	MAALI_TOOL_TYPE="tools"
+    if [[ "${MAALI_TOOL_NAME}" == "maali" ]]; then         
+	MAALI_TOOL_TYPE="tools"
         MAALI_APPS_DIR="$MAALI_ROOT/$MAALI_TOOL_TYPE"
         MAALI_TOOL_MODULE_DIR="$MAALI_MODULE_DIR/$MAALI_TOOL_TYPE/$MAALI_TOOL_NAME"
     fi 
+  fi
+else
+  echo "Warning: non-system build detected, overriding MAALI_TOOL_TYPE (currently $MAALI_TOOL_TYPE) "
+  echo "and setting to tool type to 'apps'"
+  echo " "
+  # for user builds we want them to be able to include a single module path from $MYGROUP/
+  MAALI_TOOL_TYPE="apps"
+  MAALI_APPS_DIR="$MAALI_ROOT/$MAALI_TOOL_TYPE"
+
+  if [ $MAALI_CUDA_BUILD -eq 1 ]; then
+    MAALI_TOOL_MODULE_DIR="$MAALI_MODULE_DIR/$MAALI_TOOL_NAME-gpu"
+  else
+    MAALI_TOOL_MODULE_DIR="$MAALI_MODULE_DIR/$MAALI_TOOL_NAME"    
   fi
 fi
 
@@ -2041,14 +2087,15 @@ if [ $MAALI_UNINSTALL_REMOVE -eq 1 ]; then
 fi
 
 if [ $MAALI_REMODULE -eq 0 ]; then
-  maali_wiki "creating module in $MAALI_TOOL_MODULE_DIR"
+  maali_wiki " "
+  maali_wiki "creating module in $MAALI_TOOL_MODULE_DIR line 2048"
 else
   if [ $MAALI_UNINSTALL_REMOVE -eq 1 ]; then
     echo "purging the module from $MAALI_TOOL_MODULE_DIR"
   elif [ $MAALI_UNINSTALL_HIDE -eq 1 ]; then
     echo "hiding the module in $MAALI_TOOL_MODULE_DIR"
   else
-    echo "creating module in $MAALI_TOOL_MODULE_DIR line 2050 "
+    echo "creating module in $MAALI_TOOL_MODULE_DIR line 2055 "
   fi
 fi
 
